import 'dotenv/config';
export const DATABASE_URL = process.env.DATABASE_URL;

console.log(
  '\n',
  {
    DATABASE_URL: DATABASE_URL,
    // REDIS_URL: REDIS_URL,

    // ACCESS_TOKEN_SECRET: ACCESS_TOKEN_SECRET,
    // REFRESH_TOKEN_SECRET: REFRESH_TOKEN_SECRET,

    // GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID,
    // GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET,

    // ELASTIC_SEARCH_URL: ELASTIC_SEARCH_URL,
    // ELASTIC_SEARCH_USERNAME: ELASTIC_SEARCH_USERNAME,
    // ELASTIC_SEARCH_PASSWORD: ELASTIC_SEARCH_PASSWORD,

    // RABBIT_MQ_URL: RABBIT_MQ_URL,
  },
  '\n',
);
